/* 
  Sketch generated by the Arduino IoT Cloud Thing "Smart Garden"
  https://create.arduino.cc/cloud/things/ca8fbe4d-6558-4a99-af3c-1fbb3ff02266 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float temperature;
  int light;
  int moisture;
  bool artificial_light;
  bool cooling_fan;
  bool waterpump;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_MKRIoTCarrier.h>

String waterPumpState;
String coolingFanState;
String lightState;

int moistPin = A5;
MKRIoTCarrier carrier;

uint32_t lightOn = carrier.leds.Color(82, 118, 115);
uint32_t lightOff = carrier.leds.Color(0, 0, 0);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  while(ArduinoCloud.connected() != 1) {
    ArduinoCloud.update();
    delay(500);
  }
  delay(500);
  CARRIER_CASE = false;
  carrier.begin();
  carrier.display.setRotation(0);
  delay(1500);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  temperature = carrier.Env.readTemperature();
  humidity = carrier.Env.readHumidity();
  
  int raw_moisture = analogRead(moistPin);
  
  moisture = map(raw_moisture, 0, 1023, 100, 0);
  
  while(!carrier.Light.colorAvailable()) {
    delay(5);
  }
  
  int none;
  carrier.Light.readColor(none, none, none, light);
  delay(100);
}

/*
  Since ArtificialLight is READ_WRITE variable, onArtificialLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onArtificialLightChange()  {
  if(artificial_light == true) {
    carrier.leds.fill(lightOn, 0, 5);
    carrier.leds.show();
    lightState = "Lights: ON";
  } else {
    carrier.leds.fill(lightOff, 0, 5);
    carrier.leds.show();
    lightState = "Lights: OFF";
  }
  updateScreen();
}
/*
  Since CoolingFan is READ_WRITE variable, onCoolingFanChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCoolingFanChange()  {
  if(cooling_fan == true) {
    carrier.Relay1.open();
    coolingFanState = "cooling fan : TRUE";
  } else {
    carrier.Relay1.close();
    coolingFanState = "cooling fan : FALSE";
  }
  updateScreen();
}
/*
  Since Waterpump is READ_WRITE variable, onWaterpumpChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWaterpumpChange()  {
  if (waterpump == true) {
    carrier.Relay2.open();
    waterPumpState = "Pump: ON";
  } else {
    carrier.Relay2.close();
    waterPumpState = "Pump: OFF";
  }
  updateScreen();
}

void updateScreen() {
  carrier.display.fillScreen(ST77XX_BLACK);
  carrier.display.setTextColor(ST77XX_WHITE);
  carrier.display.setTextSize(3);
  
  carrier.display.setCursor(40,50);
  carrier.display.print(waterPumpState);
  delay(500);
  carrier.display.setCursor(40,90);
  carrier.display.print(coolingFanState);
  delay(500);
  carrier.display.setCursor(40,130);
  carrier.display.print(lightState);
}







